version: '3'
services:c
  workstation:
    image: hossein20s/docker-workstation:unity3D
    container_name: workstation
#     command: tail -f /dev/null
    privileged: true
    ports:
      - 4321:4000
    environment:
      DISPLAY: # : $DISPLAY # for mac DISPLAY=docker.for.mac.host.internal:0 # --before running docker-compose and after running xhost +
      XAUTHORITY: /tmp/.docker.xauth
      USER: developer
      PASSWORD: developer
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${HOME}:/opt/host
      - /dev/shm:/dev/shm
      - ${HOME}/docker-workstation/Ubuntu-20.04/cdeveloper:/home/developer # uncomment to persists user home
      # the following is for X11 DISPLAY from http://wiki.ros.org/docker/Tutorials/GUI
      # you need to : touch /tmp/.docker.xauth
      # xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f /tmp/.docker.xauth nmerge -
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauthx


